- name: Print Task and Play level variables
  hosts: local
  connection: local
  vars:
    NAME: Sahithi
    AGE: 3
    SCHOOL: LMS
  tasks:
    - name: Print Task level vars
      vars:
        NAME: Nihal
        AGE: 10
        SCHOOL: TPS
      ansible.builtin.debug:
        msg: "Name is {{ NAME }}, Age is {{ AGE }}, School is {{ SCHOOL }}""
