- name: Install Packages
  hosts: web
  become: yes
  tasks:
  - name: Install Packages
    ansible.builtin.package:
      name: "{{ item }}"
      state: installed
    loop:
    - gcc
    - git
    - zip
    - mysql