- name: filters
  hosts: local
  connection: local
  tasks:
  - name: Handle undefined variables
    ansible.builtin.debug:
      msg: "Hello  {{ person | default('Suresh')}}" # person is not defined so it will take default value mentioned as "Suresh".

    